export const REQUEST_SENT = 'REQUEST_SENT';
export const REQUEST_FAIL = 'REQUEST_FAIL';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const EMPLOYEE_DATA_RECEIVED = 'EMPLOYEE_DATA_RECEIVED';
export const SET_FILTER = 'SET_FILTER';
export const IS_SELECTED_ROW = 'IS_SELECTED_ROW';
export const SET_ROW_ID = 'SET_ROW_ID';
export const ADD_EMP_SELECTED = 'ADD_EMP_SELECTED';
export const ADD_NEW_EMPLOYEE = 'ADD_NEW_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';

